name: "Go Service Template"

on:
  workflow_call:
    inputs:
      service_path:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
          cache-dependency-path: ${{ inputs.service_path }}/go.sum

      - name: Run Tests with Race Detector
        run: |
          cd ${{ inputs.service_path }}
          go test -v -race ./...