name: "Service: Accounts"

on:
  push:
    branches: [ main ]
    paths:
      - 'services/accounts/**' # SÓ RODA SE MUDAR AQUI
  pull_request:
    branches: [ main ]
    paths:
      - 'services/accounts/**'

jobs:
  call-go-template:
    uses: ./.github/workflows/_go-service-template.yml
    with:
      service_path: "services/accounts"